# 
version: '3.7'
services:
    be:
        build:
            context: ./be
            dockerfile: Dockerfile
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: v2
            DB_USERNAME: root
            DB_PASSWORD: 

        links:
            - db
        ports:
            - 8000:8000
        volumes:
            - ./be:/app/be
        networks:
            - app
        depends_on:
            - db
    fe:
        build:
            context: ./fe
            dockerfile: Dockerfile
        tty: true

        ports:
            - 3000:3000

        volumes:
            - ./fe:/app/fe
        
        depends_on:
            - be
        networks:
            - app

    db:
        image: mysql:latest
        ports:
            - 3308:3308
        environment:
            MYSQL_DATABASE: 'v2'
            MYSQL_ROOT_PASSWORD: 

        volumes:
            - .dbdata:/var/lib/mysql/
        networks:
            - app

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:latest
        restart: always
        links:
            - db
        ports:
            - 8090:80
        environment:
            PMA_HOST : db
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: 
        networks:
            - app
        volumes:
            - ./phpmyadmin:/var/lib/phpmyadmin/
         
networks:
    app:
        driver: bridge
