import Card from 'react-bootstrap/Card';
import Placeholder from 'react-bootstrap/Placeholder';

function TableSpinner() {
    
  return (
    <>
      <Card.Body>
        <Placeholder as={Card.Text} animation="glow">
            <Placeholder  className='border-info' xs={12} style={{"padding": "2%","marginTop":"-20px"}}>
                <Placeholder className='border-info bg-white' style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white' style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} /> <Placeholder className='border-info bg-white'  style={{"height":"25px","borderRadius":"30px"}} xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> 
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
                <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} /> <Placeholder className='border-info bg-white' xs={1} />
            </Placeholder> 
        
        </Placeholder>
      </Card.Body>
    </>
  );
}

export default TableSpinner;